### ISSUE TITLE
Push Notification Redirection Error 302

### ISSUE THREAD

**Issue by ferryfernandez** [harrypujianto/Veritrans-Laravel5#19]
Hello, semua sudah berjalan baik.. 
tetapi kenapa push notificationnya memberikan status error ya?

> Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead. Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead

note : IP sudah whitelist melalui trustedproxy

**Comment by harrypujianto** [comment]
sebaiknya tidak menggunakan redirection di notif url, sehingga tidak menghasilkan error 300

**Comment by ferryfernandez** [comment]
@harrypujianto redirection yang dimaksud seperti apa ya pak? karna saya cuma mengconfigurasa URL Notif di MAP dan diarahkan ke controller saya. didalam controllernya tidak ada redirection sama sekali. Terima kasih :D

**Comment by harrypujianto** [comment]
apakah diarahkan kesini? 

Route::post('/vt_notif', 'PagesController@notification');

**Comment by ferryfernandez** [comment]
Yes diarahkan ke seperti itu, tetapi PagesController diganti ke controller saya

**Comment by rifkirinaldi** [comment]
@ferryfernandez  udah ketemu solusinya mas ?

saya errornya malah : Response status is '419' not '200'

**Comment by syehbiherbian** [comment]
sama gan saya juga errornya seperti ini, padahal sebelumnya baik baik aja

**Comment by HengkyTetraSihotang** [comment]
[06-Jun-2018 04:03:29 Asia/Jakarta] PHP Fatal error:  Uncaught Exception: Veritrans Error ():  in /home/banm4721/public_html/payment/Veritrans/ApiRequestor.php:106
Stack trace:
#0 /home/banm4721/public_html/payment/Veritrans/ApiRequestor.php(17): Veritrans_ApiRequestor::remoteCall('https://api.san...', 'SB-Mid-server-n...', false, false)
#1 /home/banm4721/public_html/payment/Veritrans/Transaction.php(17): Veritrans_ApiRequestor::get('https://api.san...', 'SB-Mid-server-n...', false)
#2 /home/banm4721/public_html/payment/Veritrans/Notification.php(22): Veritrans_Transaction::status(NULL)
#3 /home/banm4721/public_html/payment/get_process_status.php(7): Veritrans_Notification->__construct()
#4 {main}
  thrown in /home/banm4721/public_html/payment/Veritrans/ApiRequestor.php on line 106

Mohon bantu gan ...

Thanks

**Comment by syehbiherbian** [comment]
Settingan urlnya udah bener belom gan?

**Comment by vaniawahyu** [comment]
@rifkirinaldi kalau error 419, url untuk midtrans perlu diexclude pada file di laravel: `Http/Middleware/VerifyCsrfToken.php`

**Comment by erwinyusrizal** [comment]
ada update ga gan solusi error redirection ini?

**Comment by yuliantosb** [comment]
I get the same issue here
itu kenapa ya pak?
Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead
padahal, sebelum-sebelum nya nggak pernah error seperti itu, ada yang udah solve?

**Comment by harrypujianto** [comment]
Untuk issue 3xx silahkan di pastikan jika notif url dibuka di browser tidak redirect ke website lain. untuk di repo ini, routenya diarahkan kesini
https://github.com/harrypujianto/Veritrans-Laravel5/blob/master/app/Http/Controllers/VtwebController.php#L101

**Comment by yuliantosb** [comment]
Terimakasih pak :)

**Comment by agamaeroasia** [comment]
saya menggunakan midtrans untuk 3 web saya,
notification url nya harus memanggil function masing-masing web saya. 
nah redirect nya supaya bisa jalan gimana pak?  @harrypujianto

**Comment by harrypujianto** [comment]
Seharusnya 1 website menggunakan 1 midtrans account. 
untuk tiap account, notif url dapat di set di
setting->configuration->notification url.

**Comment by ferryfernandez** [comment]
Sorry baru  read lagi issue ini, jika mengalami masalah seperti ini kemungkinan besar missmatch CSRFToken saja. Solusinya 

1. daftarkan route notification yg digunakan ke variable $except pada middleware verifyCSRFToken.
2. jika masih mengalami masalah di function handle() tambahkan kondisi $request->is

contoh

```
//myroute 'payment/notification' change to your's
if ($request->is('payment/notification')){
   return $this->addCookieToResponse($request, $next($request));
}
```

semoga membantu

**Comment by agamaeroasia** [comment]
sudah bisa pak.. saya menggunakan curl untuk mengupdate data di web yang satunya.
berikut scriptnya: 

```
function notification(){
        $r = file_get_contents("php://input"); // ambil feedback dari midtrans
        $datamid = json_decode($r);
        $order_id= $datamid->order_id;    

        //cek konfigurasi redirect url sesuai order_id milik web apa di database saya
        $sql = $this->db->query("SELECT link_notif FROM config WHERE order_id='$order_id' ");
        $hasil = $sql->row_array();
        $link = $hasil['link_notif']. "?order_id=".$order_id;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $link);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($datamid));
        $output = curl_exec($ch);
        curl_close($ch);
}
```

semoga membantu

**Comment by rayrizaldi** [comment]
Klo login terus ada bacaan, ip addres tidak ada pada whitelist, padahal sebelumnya tdak terjadi apa2, klo kaya gtu cara mengatasinya biar bisa login kembali bagaimna yah???

**Comment by syahidfrd** [comment]
Post notification tiba-tiba error ya sebelum-sebelumnya lancar saja. Pesan error di riwayat HTTP notification cuman **:killed :killed**. Tapi pas tak coba di mode sanbox lancar-lancar aja.

Terimkasih, ada solusi?

**Comment by RaflyLesmana3003** [comment]
apakah untuk error 3xx sudah ada yang bisa ngesolve?

**Comment by ajimatahari** [comment]
saya menemui ini, setelah debug, ada kesalahan di ketelitian saya:
route untuk penerima notification handling, saya masukkan di middleware auth. otomatis ketika sandbox mengirimkan notification, akan teredirect ke login (302). setelah saya pindahkan dari auth, murni di web, notification bisa masuk. hanya saja muncul kekuatiran, ketika tidak ada pengautentifikasi di penerima handling, potensi kena bruteforce jadi kebuka.

**Comment by fakhrurraziandi** [comment]
Hallo, saya  nemuin hal yg sama, yaitu "Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead."

saya sudah coba hit endpoint nya dan tidak ada redirection apapun .. tapi tetap menghadapi masalah ini.

sudah saya coba hit dari postman dengan data post yg sama persis, tidak terjadi redirect

**Comment by heyitsmi** [comment]
ada sudah solve ? saya juga menemui error seperti ini Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead. Redirection status code 301, 302 and 303 are not sup

**Comment by vaniawahyu** [comment]
saya sementara menggunakan `\Veritrans_Transaction::status`.
ada di dokumentasi PHP [step 5](https://docs.midtrans.com/en/snap/integration_php_manual.html).

semoga membantu.

**Comment by intiphp** [comment]
Saya juga mengalami masalah yang sama. Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead. 
dan solusi nya menggati url yg awal nya http:// menjadi https:// dan work.
baru ingat di htaccess ada redirect http menjadi https tenyata itu masalah nya.

**Comment by zairisatria** [comment]
saya mengalami masalah yang sama status code 301,302,303 di CI4.. saya cek saya matikan fungsi csrf tokennya, saya lakukan pembayaran notifikasinya sukses. jadi masalahnya ada di csrf token. cuma saya belum dapat solusi gimana supaya tetap bisa menggunakan csrf tokennya

**Comment by kwul0208** [comment]
hallo, saya menemui hal seperti itu ketika menggunakan CI3. sudah solve dengan cara menggunakan controller terpisah. 

controller Notification

semoga membantu

**Comment by herupurwito** [comment]
> saya menemui ini, setelah debug, ada kesalahan di ketelitian saya: route untuk penerima notification handling, saya masukkan di middleware auth. otomatis ketika sandbox mengirimkan notification, akan teredirect ke login (302). setelah saya pindahkan dari auth, murni di web, notification bisa masuk. hanya saja muncul kekuatiran, ketika tidak ada pengautentifikasi di penerima handling, potensi kena bruteforce jadi kebuka.

wah nice, ternyata saya juga teledor, masuk middleware auth haha
